pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'hvdini-recover' }
    stages {
        stage('Test') {
	    options { timeout(time: 120, unit: 'SECONDS') }
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}
